### ISSUE TITLE
Random PCFG bugs occur

### ISSUE THREAD

**Issue by TrakJohnson** [TrakJohnson/tpe-website-and-server#1]
Probably because the dict doesn't like having objects as keys

**Comment by TrakJohnson** [comment]
If we can't change this behaviour, emergency plan is to convert all keys to str (but its kindof annoying)

**Comment by Pyxidatol-C** [comment]
AHH D'ACCORD PFF THIS IS WHERE THE BUGS COME FROM

**Comment by TrakJohnson** [comment]
Yup this is where it comes from. I think I'll give up and convert all to strings, there really isn't any point in keeping them as objects anyways.

**Comment by TrakJohnson** [comment]
fd233120597291b0e35359c3b51a0164dd8e4e18
